### ISSUE TITLE
having issue wlan

### ISSUE THREAD

**Issue by ashishjohnson** [AshishM94/Santoni#1]
try turn ON hotspot while mobile data is on and try turn off hotspot and try again to turn on wifi without turn off mobile data

**Comment by ashishjohnson** [comment]
Having same issue with stock kernel 3.18.31 problem belongs to prima

**Comment by AshishM94** [comment]
Hotspot works fine. The only issue I encountered was I couldn't change security to WPA2-PSK which basically means anyone can use my data without authorisation.
![screenshot_2018-04-14-12-21-58-753_com android settings](https://user-images.githubusercontent.com/22554229/38765428-e4f49bb4-3fde-11e8-9c43-8ae7b2a2fd5e.png)

**Comment by AshishM94** [comment]
Edit: Even WPA2-PSK works. Just had to set the password with 8 characters lol.
![screenshot_2018-04-14-12-33-25-008_com android settings](https://user-images.githubusercontent.com/22554229/38765487-20895f56-3fe0-11e8-883d-3e7f401fe330.png)
![screenshot_2018-04-14-12-33-36-344_com android settings](https://user-images.githubusercontent.com/22554229/38765488-20f55a26-3fe0-11e8-86ec-b14987ac5e61.png)

**Comment by ashishjohnson** [comment]
But i could fix security in my kernel without fail but having problem faceing turn on hotpot while mobile data is stay on its only working for i single time after turnoff hotspot and i tried to connect again wifi then wlan is not responding
